[workspace]
[package]
name = "a-coroutine-bonus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummy-waker = "1.1.0"
mio = { version = "0.8.9", features = ["net", "os-poll"] }